### ISSUE TITLE
remove momentjs from project

### ISSUE THREAD

**Issue by bennigames** [roccivic/cron-converter#17]
since the momentjs project even suggest to use other libraries it would be perfect to replace moment in this project with a smaller library (see: https://momentjs.com/docs/#/-project-status/)

**Comment by roccivic** [comment]
Thanks @bennigames. I'll have a look.

**Comment by bennigames** [comment]
> Thanks @bennigames. I'll have a look.

any update on this? just asking for a friend <.< :-)

**Comment by roccivic** [comment]
I started looking at what's involved last weekend.

Since removing moment requires a breaking change to the API, I am considering bundling a few other breaking changes together and aiming for a major release. I'm experimenting in the [next branch](https://github.com/roccivic/cron-converter/commits/next). So far I think I want:
* Functional API and immutability
* Typescript port with bundled types
* Removal of sprintf-js
* Better algorithm for `next()`/`prev()`

**Comment by missing1984** [comment]
Any progress on this one?

**Comment by roccivic** [comment]
I understand the implications of depending on moment for creating bundles. I have not made any progress on this issue, and unfortunately don't expect to be able to make further progress any time soon. Contributions to the project are welcome as always.

**Comment by roccivic** [comment]
I have completed the necessary changes in the [next](https://github.com/roccivic/cron-converter/tree/next) branch.
Feel free to check it out, I will publish that as version `2.0.0` soon.

**Comment by roccivic** [comment]
Fixed in `2.0.0`
